export const CREATE_WAIT_ERROR = 'CREATE_WAIT_ERROR';
export const CREATE_WAIT_SUCCESS = 'CREATE_WAIT_SUCCESS';

export const REMOVE_WAIT_ERROR = 'REMOVE_WAIT_ERROR';
export const REMOVE_WAIT_SUCCESS = 'REMOVE_WAIT_SUCCESS';

export const UNDELETE_WAIT_ERROR = 'UNDELETE_WAIT_ERROR';

export const UPDATE_WAIT_ERROR = 'UPDATE_WAIT_ERROR';
export const UPDATE_WAIT_SUCCESS = 'UPDATE_WAIT_SUCCESS';

export const FILTER_WAITS = 'FILTER_WAITS';
export const LOAD_WAITS_SUCCESS = 'LOAD_WAITS_SUCCESS';
export const UNLOAD_WAITS_SUCCESS = 'UNLOAD_WAITS_SUCCESS';
